### ISSUE TITLE
NOT AN ISSUE 

### ISSUE THREAD

**Issue by Blipee** [be0vlk/owlculus-gui#3]
How do I buy you a coffee?? Loving your case management software.

**Comment by be0vlk** [comment]
Wow so sorry I'm only just now seeing this. Good job on the notifications GitHub! Glad you're enjoying it though, development has temporarily slowed down but still much more to come. And thanks so much for the offer but I set out to make this 100% free and open source, forever, so as long as you keep enjoying and getting good use out of it that's all I need :)
